CREATE TABLE CONTRATOS(
	ID_CONTRATO SERIAL NOT NULL,
	VALOR_PARCELA FLOAT NOT NULL,
	PARCELAS INT NOT NULL,
	PRIMARY KEY(ID_CONTRATO)
);

CREATE TABLE PESSOAS(
	ID_PESSOA SERIAL NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	ID_CONTRATO INT NOT NULL,
	INADIMPLENTE VARCHAR(1) NOT NULL,
	DT_COMPLETO DATE,
	PRIMARY KEY(ID_PESSOA),
	FOREIGN KEY(ID_CONTRATO) REFERENCES CONTRATOS(ID_CONTRATO)
);

CREATE TABLE PAGAMENTOS(
	ID_PAGAMENTO SERIAL NOT NULL,
	ID_PESSOA INT NOT NULL,
	DT_PAGAMENTO DATE NOT NULL,
	PRIMARY KEY(ID_PAGAMENTO),
	FOREIGN KEY(ID_PESSOA) REFERENCES PESSOAS(ID_PESSOA)
);

	
INSERT INTO CONTRATOS(VALOR_PARCELA, PARCELAS)
VALUES
	(150, 100),
	(300, 48),
	(550, 24),
	(1000, 12);


INSERT INTO PESSOAS(NOME, ID_CONTRATO, INADIMPLENTE, DT_COMPLETO)
VALUES
	('Cristian Ghyprievy', 2, 'S', NULL),
	('Joana Cabel', 1, 'S', NULL),
	('John Serial', 3, 'S', NULL),
	('Michael Seven', 2, 'N', '2021-09-25');
	
	
INSERT INTO PAGAMENTOS(ID_PESSOA, DT_PAGAMENTO)
VALUES
	(4, '2021-09-01'),
	(3, '2021-09-05'),
	(1, '2021-09-19'),
	(2, '2021-09-25');