SELECT PE.NOME, EXTRACT(DAY FROM DT_PAGAMENTO) AS "DIA_MES", CR.VALOR_PARCELA
FROM CONTRATOS CR
INNER JOIN PESSOAS PE
ON PE.ID_CONTRATO = CR.ID_CONTRATO
INNER JOIN PAGAMENTOS PA
ON PA.ID_PESSOA = PE.ID_PESSOA
WHERE PE.INADIMPLENTE != 'N'
ORDER BY PE.NOME ASC;